language: python
python:
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - "pip install -e ."
    - "pip install git+https://github.com/jmcgeheeiv/pyfakefs"
script:
    - "python ./setup.py nosetests"
